FROM node:22.12-alpine AS build
WORKDIR /app
RUN corepack enable
COPY package*.json ./
RUN npm ci
COPY . .
ARG VITE_MAIN_DOMAIN=localhost
ARG VITE_API_BASE_URL=
ENV VITE_MAIN_DOMAIN=$VITE_MAIN_DOMAIN
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
RUN npm run build

FROM nginx:1.27-alpine
ENV UPLOAD_MAX_TOTAL_SIZE_BYTES=0
COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/prod/nginx.prod.conf /etc/nginx/templates/default.conf.template
EXPOSE 80
